# File syntax : https://docs.docker.com/compose/compose-file/
# Global config, you can add your <ENV>.yml to override this one with -f option.

version: "3.6"

services:

  http:
    build: ./docker/nginx
    container_name: nginx
    working_dir: /srv
    restart: always
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: php
    working_dir: /srv
    restart: always
